import random
import os
from Crypto.Hash import SHA256
from base64 import b64encode
from urllib.parse import urlencode
import requests
from datetime import datetime, timedelta

from flask import session
from app import db
from app.models import User
from flask_login import current_user

"""
USAGE GUIDE

GETTING A TOKEN TO USE FOR AN API REQUEST
    
    call auth.getCurrentToken() and use the return value as the token

    if the user has not been authorized getCurrentToken() will raise a
    UserNotAuthorizedError

    if the refresh token used to request a token refresh is outdated it will
    raise a BadRefreshTokenError

YOU SHOULD NOT NEED TO USE ANY OTHER METHOD MANUALLY OR ACCESS ANY PART OF AUTH
"""
class UserNotAuthroizedError(Exception):
  pass

class BadRefreshTokenError(Exception):
  pass

#region Token
class AuthToken:
  def __init__(self):
    # Use environment variables in deployed environments (Docker/AWS) to avoid hard-coding.
    # Defaults keep local development working.
    self.client_id = os.environ.get("SPOTIFY_CLIENT_ID") or "5fde8f3f1dd64da78756642ebe41338a"
    self.redirect_uri = os.environ.get("SPOTIFY_REDIRECT_URI") or "http://127.0.0.1:5000/auth"
    self.code_verifier = ""
    self.code_challenge = ""
    self.auth_code = ""
    # after user has been authorized the below are all that should ever be altered
    self.access_token = ""
    self.refresh_token = ""
    self.time_token_granted = ""

#endregion

#region Get Auth Code
  """
  Generates a random alphanumeric string of length passed to funciton.
  """
  def generateRandomString(self, length):
    available_characters = "ABCDEFGHIJKLMNOPQRSTUVWXZYabcdefghijklmnopqrstuvwxyz0123456789"
    available_characters_length = len(available_characters)
    random_string = ""
    random_int = 0
    for i in range(0,length):
      random_int = random.randint(0, available_characters_length-1)
      random_string += available_characters[random_int]
    return random_string
  
  """
  Performs a sha256 hash on some input.
  """
  def sha256(self, input):
    data = input.encode("utf-8")
    hash = SHA256.new()
    hash.update(data)
    return hash.digest()
  
  """
  Encodes a hash into base64 that works with the Spotify API.
  """
  def base64encode(self, input):
    return b64encode(input).decode().replace("=","").replace("+","-").replace("/","_")
  
  """
  Generates the code challenge that the spotify API uses to authorize user.
  
  Input should be a random string of length 128 generated by generateRandomString()
  """
  def generateCodeChallenge(self, input):
    hashed = self.sha256(input)
    code_challenge = self.base64encode(hashed)
    return code_challenge
  
  """
  Generates the URL that allows the user to authorize the app to use the spotify API with
  their account.

  User should then be redirected to this address to get permission.
  
  After confirm or deny, user will be redirected back to self.redirect_uri 
  (currently http:127.0.0.1:5000/auth)

  At the redirect uri, spotify will add the authorization code as a query paramter.
  """
  def generateAuthURL(self):
    self.code_verifier = self.generateRandomString(128)
    self.code_challenge = self.generateCodeChallenge(self.code_verifier)
    # Persist PKCE verifier across redirects (and across gunicorn workers/containers).
    session['spotify_code_verifier'] = self.code_verifier
    url = "https://accounts.spotify.com/authorize"
    params = {
      "client_id": self.client_id,
      "response_type": "code",
      "redirect_uri": self.redirect_uri,
      "scope": "playlist-read-private playlist-read-collaborative user-top-read user-read-recently-played user-library-read",
      "code_challenge_method": "S256",
      "code_challenge": self.code_challenge
    }
    auth_url = url + "?" + urlencode(params)
    return auth_url
#endregion

#region Access Token
  """
  Uses the code obtained from the authorization to request an access token from the Spotify API.
  """
  def requestAccessToken(self):
    code_verifier = session.get('spotify_code_verifier') or self.code_verifier
    if not code_verifier:
      raise UserNotAuthroizedError
    url = "https://accounts.spotify.com/api/token"
    headers = {
      "Content-Type": "application/x-www-form-urlencoded"
    }
    data = {
      "grant_type": "authorization_code",
      "code": self.auth_code,
      "redirect_uri": self.redirect_uri,
      "client_id": self.client_id,
      "code_verifier": code_verifier
    }
    return requests.post(url, headers=headers, data=data)
  
  """
  Parses json token into the access token and refresh token.
  
  Stores the time the token was granted so that we can refresh the token before it expires.
  """
  def setCurrentToken(self, data):
    if 'access_token' not in data:
      raise Exception(f"Spotify token response missing access_token: {data}")

    self.access_token = data['access_token']
    # Refresh responses often omit refresh_token; keep the existing one in that case.
    if 'refresh_token' in data and data['refresh_token']:
      self.refresh_token = data['refresh_token']
    self.time_token_granted = datetime.now()
    self.storeToken()
    return self.time_token_granted
  
  """
  Completes the necessary steps to gaining access to the Spotify API after user has confirmed
  authorization.
  """
  def completeAuth(self, code):
    self.auth_code = code
    response = self.requestAccessToken()
    try:
      data = response.json()
    except Exception:
      data = {"error": "non_json_response", "body": response.text}

    if not response.ok:
      print(data)
      raise Exception(f"Spotify access token request failed: {data}")

    # No longer needed after exchanging the auth code.
    session.pop('spotify_code_verifier', None)
    return self.setCurrentToken(data)
#endregion

#region Refresh Token
  """
  Request a token refresh from the Spotify API.
  """
  def requestTokenRefresh(self):
    if not self.refresh_token:
      raise UserNotAuthroizedError
    url = "https://accounts.spotify.com/api/token"
    headers = {
      "Content-Type": "application/x-www-form-urlencoded"
    }
    data = {
      "grant_type": "refresh_token",
      "refresh_token": self.refresh_token,
      "client_id": self.client_id
    }
    return requests.post(url, headers=headers, data=data)
  
  """
  Gets a new token from the SpotifyAPI and sets the current token fields to the new token.
  """
  def refreshCurrentToken(self):
    response = self.requestTokenRefresh()
    try:
      data = response.json()
    except Exception:
      data = {"error": "non_json_response", "body": response.text}

    if not response.ok:
      print(data)
      # Typically means we tried to refresh without a stored refresh token.
      if data.get('error') == 'invalid_request' and 'refresh_token' in str(data.get('error_description', '')):
        raise UserNotAuthroizedError
      raise BadRefreshTokenError

    return self.setCurrentToken(data)
#endergion

#region Store Token
  """
  Stores a token in the session.
  """
  def storeSessionToken(self): 
    session['refresh_token'] = self.refresh_token # this is still used for checking if the user is authenticated or not
    current_user.refresh_token = self.refresh_token
    return current_user.refresh_token
  
  """
  Stores the refresh token in the database.
  """
  def storeDatabaseToken(self):
    user_id = current_user.user_id
    user = User.query.get(user_id)
    user.refresh_token = self.refresh_token
    db.session.commit()
  
  """
  Stores a token in the session, and the refresh token in the database.
  """
  def storeToken(self):
    self.storeSessionToken()
    self.storeDatabaseToken()
#endregion

#region Restore Token
  """
  Restores auth from a session token.

  Returns false if no session_token exists.
  """
  def restoreSessionToken(self):
    print("DEBUG: Attempting to restore session token")
    refresh_token = session.get('refresh_token')
    if not refresh_token:
      print("DEBUG: Session token NOT FOUND")
      return False

    self.refresh_token = refresh_token
    print("DEBUG: Session token FOUND")
    try:
      print("DEBUG: Attempting refresh")
      self.refreshCurrentToken()
      print("DEBUG: Refresh succesful")
      return True
    except BadRefreshTokenError:
      print("DEBUG: Refresh from session token failed")
      raise BadRefreshTokenError

  """
  Restores auth from database token. Assumes user is logged in.

  Returns false if user has not been authorized.
  """
  def restoreDatabaseToken(self):
    print("DEBUG: Attemping to restore token from database")
    if not getattr(current_user, 'is_authenticated', False):
      print("DEBUG: No authenticated user")
      return False

    user_id = current_user.user_id
    user = User.query.get(user_id)
    if user is None:
      print("DEBUG: User not found")
      return False
    
    print("DEBUG: User session token found")
    refresh_token = user.refresh_token
    if not refresh_token:
      print("DEBUG: No refresh token found")
      return False
    
    self.refresh_token = refresh_token
    try:
        print("DEBUG: Attempting refresh")
        self.refreshCurrentToken()
        print("DEBUG: Refresh succesful")
    except BadRefreshTokenError:
        print("DEBUG: Refresh from database failed")
        raise BadRefreshTokenError
    return True

  """
  Restores auth from previous usage (session or database if no token in session).

  Returns false if the user has not been authorized.
  """
  def restoreToken(self):
    try:
      if (self.restoreSessionToken()):
        return True
      return self.restoreDatabaseToken()
    except BadRefreshTokenError:
        raise BadRefreshTokenError
#endregion

#region Current Token
  """
  Gets a current token. If current token is close to expiring, requests a new one.

  Raises an exception if user has not been authorized.
  """
  def getCurrentToken(self):
    # check if this is a fresh auth instance
    print("DEBUG: Checking for existing access token")
    if (self.access_token == ""):
      print("DEBUG: Access token not found")
      # restore the auth state from stored token
      try:
        if (not self.restoreToken()):
          raise UserNotAuthroizedError
      except BadRefreshTokenError:
        raise BadRefreshTokenError
    
    print("DEBUG: access token found")
    # get the current token
    current_time = datetime.now()
    # token expires in 60 minutes so refresh every 55 to be safe
    if ((current_time - self.time_token_granted) > timedelta(minutes=55)):
      self.refreshCurrentToken()
    return self.access_token
#endregion

#region Management
class Auth:
  def __init__(self):
    self.user_tokens = {}

  def getCurrentUserToken(self):
    try:
      return self.user_tokens[current_user.user_id]
    except KeyError:
      self.user_tokens[current_user.user_id] = AuthToken()
      return self.user_tokens[current_user.user_id]
    
  def removeUserToken(self):
    try:
      self.user_tokens.pop(current_user.user_id)
    except KeyError:
      pass
  
  def generateAuthURL(self):
    return self.getCurrentUserToken().generateAuthURL()
  
  def completeAuth(self, code):
    return self.getCurrentUserToken().completeAuth(code)
  
  def getCurrentToken(self):
    return self.getCurrentUserToken().getCurrentToken()
#endregion

auth = Auth()